language: java
jdk:
  - oraclejdk8
before_deploy:
  - gradle test
  - ls $TRAVIS_BUILD_DIR
deploy:
  provider: s3
  access_key_id: $TravisAccessKey
  secret_access_key: $TravisSecretAccessKey
  bucket: billyjf.functional-tests.junit
  local_dir: $TRAVIS_BUILD_DIR/build/reports/tests/test
  on:
    all_branches: true