language: java
jdk:
  - oraclejdk8
script: gradle test --stacktrace
deploy:
  provider: s3
  region: us-west-2
  access_key_id: $TravisAccessKey
  secret_access_key: $TravisSecretAccessKey
  bucket: billyjf.functional-tests.junit
  skip_cleanup: true
  acl: public_read
  local_dir: build/reports/tests
  on:
    all_branches: true
#addons:
#  artifacts:
#    #bucket: "billyjf.functional-tests.junit"
#    #key: $TravisAccessKey
#    #secret: $TravisSecretAccessKey
#    s3_region: "us-west-2"
#    debug: true